version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: clojure:alpine
    environment:
      LEIN_ROOT=nbd
    steps:
      - checkout
      - restore_cache:
          key: << checksum "project.clj" >>
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: << checksum "project.clj" >>
      - run: |
          lein test
          lein cljsbuild once min
